import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import { scholarshipsTable, examsTable, resourcesTable, mentorsTable } from "../../lib/db/src/schema/index.js";

const { Pool } = pg;

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const db = drizzle(pool);

async function seed() {
  console.log("Seeding database with real Indian education data...");

  await db.delete(scholarshipsTable);
  await db.delete(examsTable);
  await db.delete(resourcesTable);
  await db.delete(mentorsTable);
  console.log("Cleared existing data.");

  // ─── SCHOLARSHIPS ────────────────────────────────────────────────────────────
  await db.insert(scholarshipsTable).values([
    {
      name: "Post Matric Scholarship for SC Students",
      provider: "Ministry of Social Justice & Empowerment, Govt. of India",
      amount: "Up to ₹1,200/month + tuition fees",
      deadline: "31 October 2026",
      applyUrl: "https://scholarships.gov.in/fresh/newstdRegister",
      eligibility: "SC students pursuing post-matriculation courses with family income below ₹2.5 lakh/year",
      category: "SC",
      state: null,
      stream: "all",
      description: "Central government scholarship for SC students covering maintenance allowance, study tour charges, and thesis/dissertation typing charges for all post-matric courses.",
    },
    {
      name: "Post Matric Scholarship for ST Students",
      provider: "Ministry of Tribal Affairs, Govt. of India",
      amount: "Up to ₹1,200/month + tuition fees",
      deadline: "31 October 2026",
      applyUrl: "https://scholarships.gov.in/fresh/newstdRegister",
      eligibility: "ST students at post-matriculation level with family income below ₹2.5 lakh/year",
      category: "ST",
      state: null,
      stream: "all",
      description: "Scholarship for Scheduled Tribe students to pursue post-matric education including professional and technical courses.",
    },
    {
      name: "Post Matric Scholarship for OBC Students",
      provider: "Ministry of Social Justice & Empowerment, Govt. of India",
      amount: "Up to ₹1,000/month",
      deadline: "31 October 2026",
      applyUrl: "https://scholarships.gov.in/fresh/newstdRegister",
      eligibility: "OBC students at post-matric level with family income below ₹1 lakh/year",
      category: "OBC",
      state: null,
      stream: "all",
      description: "Provides financial assistance to OBC students to enable them to complete their post-matric education including college and university level.",
    },
    {
      name: "Central Sector Scheme of Scholarship (CSSS)",
      provider: "Ministry of Education, Govt. of India",
      amount: "₹12,000/year (UG) | ₹20,000/year (PG)",
      deadline: "31 October 2026",
      applyUrl: "https://scholarships.gov.in/fresh/newstdRegister",
      eligibility: "Students in top 20 percentile of Class 12 board exams with family income below ₹8 lakh/year",
      category: "all",
      state: null,
      stream: "all",
      description: "Merit-based scholarship for students pursuing regular undergraduate or postgraduate courses (not professional courses). Awarded to top performers in board exams.",
    },
    {
      name: "Prime Minister's Scholarship Scheme (PMSS)",
      provider: "Ministry of Home Affairs, Govt. of India",
      amount: "₹3,000/month (Boys) | ₹3,500/month (Girls)",
      deadline: "15 November 2026",
      applyUrl: "https://ksb.gov.in/pmss-online-application.htm",
      eligibility: "Wards and widows of ex-servicemen/coast guard. Min. 60% marks in qualifying exam",
      category: "all",
      state: null,
      stream: "all",
      description: "Scholarship to encourage technical and professional education for wards of ex-servicemen and ex-coast guard personnel.",
    },
    {
      name: "National Scholarship for Minority Students",
      provider: "Ministry of Minority Affairs, Govt. of India",
      amount: "₹30,000/year (Professional) | ₹20,000/year (Technical)",
      deadline: "31 October 2026",
      applyUrl: "https://scholarships.gov.in/fresh/newstdRegister",
      eligibility: "Muslim, Christian, Sikh, Buddhist, Jain, or Parsi students with income below ₹2 lakh/year and min. 50% marks",
      category: "all",
      state: null,
      stream: "all",
      description: "Pre-matric and post-matric scholarships for students belonging to notified minority communities to promote education among them.",
    },
    {
      name: "Ishan Uday — Special Scholarship for North East India",
      provider: "University Grants Commission (UGC)",
      amount: "₹5,400 – ₹7,800/month",
      deadline: "30 September 2026",
      applyUrl: "https://ishan.ucanapply.in/public/index.php/site/register",
      eligibility: "Domicile of NE states pursuing general/technical/medical courses at colleges outside NE India",
      category: "all",
      state: null,
      stream: "all",
      description: "UGC scholarship for students from 8 North Eastern states pursuing higher education outside their home states to encourage mobility and integration.",
    },
    {
      name: "Begum Hazrat Mahal National Scholarship",
      provider: "Maulana Azad Education Foundation",
      amount: "₹5,000/year (Class 9-10) | ₹6,000/year (Class 11-12)",
      deadline: "30 September 2026",
      applyUrl: "https://maef.net.in/online-application.php",
      eligibility: "Minority girl students studying in Class 9–12 with income below ₹2 lakh/year and min. 50% marks",
      category: "all",
      state: null,
      stream: "all",
      description: "Scholarship specifically for meritorious girl students from minority communities to continue secondary and senior secondary education.",
    },
    {
      name: "Tamil Nadu Chief Minister's Scholarship",
      provider: "Government of Tamil Nadu",
      amount: "₹1,000 – ₹2,000/month",
      deadline: "30 September 2026",
      applyUrl: "https://tnscholarships.gov.in/Appl_Registration/studRegistration.aspx",
      eligibility: "Tamil Nadu domicile SC/ST/BC/OBC students with income below ₹2.5 lakh/year",
      category: "BC",
      state: "Tamil Nadu",
      stream: "all",
      description: "State government scholarship for meritorious students from backward classes in Tamil Nadu pursuing undergraduate and postgraduate courses.",
    },
    {
      name: "Maharashtra State SC Scholarship",
      provider: "Government of Maharashtra — Social Justice Dept.",
      amount: "Full tuition + ₹800/month maintenance",
      deadline: "31 October 2026",
      applyUrl: "https://mahaeschol.maharashtra.gov.in/Register.aspx",
      eligibility: "SC students domiciled in Maharashtra pursuing professional / technical degrees",
      category: "SC",
      state: "Maharashtra",
      stream: "all",
      description: "State scholarship covering full tuition fees and monthly maintenance allowance for SC students from Maharashtra studying professional courses.",
    },
    {
      name: "Karnataka Rajyotsava Scholarship",
      provider: "Government of Karnataka — Kannada & Culture Dept.",
      amount: "₹1,500 – ₹3,000 one-time",
      deadline: "15 December 2026",
      applyUrl: "https://ssp.karnataka.gov.in/student/registration",
      eligibility: "Karnataka domicile students with min. 85% marks in SSLC / PUC and income below ₹3.5 lakh/year",
      category: "all",
      state: "Karnataka",
      stream: "all",
      description: "Merit-based scholarship given on Rajyotsava day to students who have excelled in board examinations and hail from Karnataka.",
    },
    {
      name: "Andhra Pradesh EAMCET Merit Scholarship",
      provider: "Government of Andhra Pradesh",
      amount: "₹15,000/year",
      deadline: "30 November 2026",
      applyUrl: "https://apsche.ap.gov.in/Scholarship/Registration",
      eligibility: "AP domicile Engineering / Pharmacy students who cleared EAMCET with top ranks and income below ₹4 lakh/year",
      category: "all",
      state: "Andhra Pradesh",
      stream: "Engineering",
      description: "Scholarship for high-ranking EAMCET students in Andhra Pradesh pursuing engineering and pharmacy degrees in AP colleges.",
    },
    {
      name: "Inspire Scholarship (SHE) — DST",
      provider: "Department of Science & Technology, Govt. of India",
      amount: "₹80,000/year for 5 years",
      deadline: "31 October 2026",
      applyUrl: "https://online-inspire.gov.in/Account/Register",
      eligibility: "Students in top 1% of Class 12 boards or top 10,000 in JEE/NEET pursuing B.Sc./B.S./Int. M.Sc. in natural/basic sciences",
      category: "all",
      state: null,
      stream: "Science",
      description: "Scholarship for Excellence (SHE) under the INSPIRE scheme by DST to attract talented students to pursue basic/natural sciences at undergraduate level.",
    },
    {
      name: "Kishore Vaigyanik Protsahan Yojana (KVPY)",
      provider: "Indian Institute of Science (IISc) / DST",
      amount: "₹7,000/month (SB stream) for 3 years",
      deadline: "Applications reopen November 2026",
      applyUrl: "https://kvpy.iisc.ac.in/main/how-to-apply.htm",
      eligibility: "Students in B.Sc./B.S./B.Stat./B.Math. or Int. M.Sc. in Science who cleared KVPY aptitude test",
      category: "all",
      state: null,
      stream: "Science",
      description: "Fellowship program to identify students with research aptitude in basic sciences and support their science education with monthly stipend and annual contingency grants.",
    },
    {
      name: "EWS Scholarship — Higher Education",
      provider: "Ministry of Education, Govt. of India",
      amount: "₹10,000 – ₹20,000/year",
      deadline: "31 October 2026",
      applyUrl: "https://scholarships.gov.in/fresh/newstdRegister",
      eligibility: "General category students with family income below ₹8 lakh/year who don't get reservation benefits",
      category: "EWS",
      state: null,
      stream: "all",
      description: "Scholarship for Economically Weaker Sections in the general category pursuing higher education, introduced to provide financial assistance without reservation benefits.",
    },
    {
      name: "Aicte Pragati Scholarship for Girls",
      provider: "AICTE (All India Council for Technical Education)",
      amount: "₹50,000/year",
      deadline: "31 October 2026",
      applyUrl: "https://www.aicte-pragati-saksham-gov.in/Registration",
      eligibility: "Girl students pursuing AICTE-approved technical diplomas/degrees with family income below ₹8 lakh/year",
      category: "all",
      state: null,
      stream: "Engineering",
      description: "AICTE's Pragati scholarship for girl students in technical education covering tuition fees and incidental charges to encourage girls in STEM fields.",
    },
    {
      name: "Maulana Azad National Fellowship (MANF)",
      provider: "University Grants Commission (UGC)",
      amount: "₹31,000/month (JRF) | ₹35,000/month (SRF)",
      deadline: "31 December 2026",
      applyUrl: "https://manf.ucanapply.in/public/index.php/site/register",
      eligibility: "Minority community students pursuing M.Phil./Ph.D. who cleared UGC NET",
      category: "all",
      state: null,
      stream: "all",
      description: "Fellowship providing integrated five-year support for M.Phil. and Ph.D. students from minority communities to promote research and higher education.",
    },
    {
      name: "Rajasthan SC/ST Scholarship",
      provider: "Government of Rajasthan — Social Justice Dept.",
      amount: "Full tuition + ₹900/month",
      deadline: "30 September 2026",
      applyUrl: "https://sje.rajasthan.gov.in/Default.aspx?PageID=342",
      eligibility: "SC/ST students domiciled in Rajasthan pursuing post-matric education with income below ₹2.5 lakh/year",
      category: "SC",
      state: "Rajasthan",
      stream: "all",
      description: "Post-matric scholarship by Rajasthan state government for SC and ST students covering tuition, exam fees, and maintenance allowance.",
    },
    {
      name: "Telangana SC/BC Post Matric Scholarship",
      provider: "Government of Telangana",
      amount: "Full tuition + ₹1,000/month",
      deadline: "31 October 2026",
      applyUrl: "https://telanganaepass.cgg.gov.in/StudentRegistration.do",
      eligibility: "SC/BC students domiciled in Telangana with income below ₹2 lakh/year",
      category: "BC",
      state: "Telangana",
      stream: "all",
      description: "Telangana e-PASS scholarship scheme providing maintenance allowance and tuition reimbursement for SC and BC students pursuing higher education.",
    },
    {
      name: "West Bengal Merit-cum-Means Scholarship",
      provider: "Government of West Bengal — Education Dept.",
      amount: "₹1,500 – ₹3,500/month",
      deadline: "30 November 2026",
      applyUrl: "https://wbmcmscholarship.gov.in/registration",
      eligibility: "WB domicile students with min. 75% marks and income below ₹2.5 lakh/year",
      category: "all",
      state: "West Bengal",
      stream: "all",
      description: "West Bengal government scholarship combining merit and means to support economically weaker students in the state pursuing higher education.",
    },
  ]);
  console.log("Scholarships seeded.");

  // ─── EXAMS ───────────────────────────────────────────────────────────────────
  await db.insert(examsTable).values([
    {
      name: "NDA 2026 Exam II",
      conductedBy: "Union Public Service Commission (UPSC)",
      examDate: "September 14, 2026",
      registrationDeadline: "June 16, 2026",
      officialUrl: "https://upsc.gov.in/examinations/active-examinations",
      stream: "all",
      description: "National Defence Academy exam II for 2026 — admission to Army, Navy, and Air Force wings of NDA and Indian Naval Academy for 10+2 pass candidates.",
      careerRelevance: "Direct entry into the Indian Army, Navy, and Air Force as an officer — a prestigious career with guaranteed growth and perks.",
    },
    {
      name: "SSC CGL 2026",
      conductedBy: "Staff Selection Commission (SSC)",
      examDate: "Tier I: September–November 2026",
      registrationDeadline: "August 5, 2026",
      officialUrl: "https://ssc.gov.in",
      stream: "all",
      description: "Combined Graduate Level examination for recruitment to Group B and C posts in central government — includes Income Tax Inspector, CBI Sub-Inspector, Audit Officer.",
      careerRelevance: "Group B/C posts in Income Tax Dept., CBI, CAG, MEA with salary of ₹35,000–80,000/month and 7th Pay Commission benefits.",
    },
    {
      name: "CAT 2026 (MBA Entrance)",
      conductedBy: "IIMs (on rotation) — IIM Calcutta 2026",
      examDate: "November 23, 2026",
      registrationDeadline: "September 15, 2026",
      officialUrl: "https://iimcat.ac.in",
      stream: "Commerce",
      description: "Common Admission Test for MBA/PGDM admission to all 20 IIMs and 1,200+ other B-schools across India. Tests Verbal, DILR, and Quantitative skills.",
      careerRelevance: "Admission to IIM Ahmedabad, Bangalore, Calcutta, and all 20 IIMs plus top B-schools like FMS, MDI, SPJIMR.",
    },
    {
      name: "GATE 2027",
      conductedBy: "IIT Delhi (2027 organising institute)",
      examDate: "February 7, 8, 14, 15, 2027",
      registrationDeadline: "October 3, 2026",
      officialUrl: "https://gate2027.iitd.ac.in",
      stream: "Engineering",
      description: "Graduate Aptitude Test in Engineering for M.Tech/MS admissions at IITs, NITs, IISc. Also used for PSU recruitment by BHEL, GAIL, NTPC, etc.",
      careerRelevance: "M.Tech at IITs/NITs and direct PSU jobs at NTPC, BHEL, GAIL, IOCL, SAIL with starting salary of ₹50,000–70,000/month.",
    },
    {
      name: "IBPS PO 2026",
      conductedBy: "Institute of Banking Personnel Selection (IBPS)",
      examDate: "October 3–4, 2026 (Prelims)",
      registrationDeadline: "September 10, 2026",
      officialUrl: "https://ibps.in",
      stream: "Commerce",
      description: "Common Recruitment Process for Probationary Officer posts in public sector banks like PNB, Bank of Baroda, Canara Bank, Union Bank, etc.",
      careerRelevance: "Bank PO job at scale I officer level with starting CTC of ₹8–10 lakh/year with housing loan, medical, and other perks.",
    },
    {
      name: "SBI PO 2026",
      conductedBy: "State Bank of India (SBI)",
      examDate: "November 2026 (Prelims)",
      registrationDeadline: "September 30, 2026",
      officialUrl: "https://sbi.co.in/careers",
      stream: "Commerce",
      description: "SBI Probationary Officer recruitment — one of the most sought-after banking jobs in India. Includes Prelims, Mains, and Group Exercise & Interview.",
      careerRelevance: "Probationary Officer at India's largest bank with CTC of ₹12+ lakh/year, fast-track promotions, and housing facilities.",
    },
    {
      name: "CLAT 2027",
      conductedBy: "Consortium of National Law Universities",
      examDate: "December 6, 2026",
      registrationDeadline: "November 1, 2026",
      officialUrl: "https://consortiumofnlus.ac.in",
      stream: "Law",
      description: "Common Law Admission Test for 5-year integrated B.A. LL.B. and 1-year LL.M. programmes at all 22 National Law Universities (NLUs) in India.",
      careerRelevance: "Admission to NLU Delhi (NLUD), NALSAR, NUJS, NLIU and other top NLUs — the premier law schools in India.",
    },
    {
      name: "UGC NET December 2026",
      conductedBy: "National Testing Agency (NTA)",
      examDate: "December 2026",
      registrationDeadline: "October 15, 2026",
      officialUrl: "https://ugcnet.nta.ac.in",
      stream: "all",
      description: "University Grants Commission National Eligibility Test to determine eligibility for Assistant Professor and Junior Research Fellowship (JRF) in Indian universities.",
      careerRelevance: "Required to become an Assistant Professor in any central/state university. JRF winners get ₹31,000/month for PhD research.",
    },
    {
      name: "NEET PG 2027",
      conductedBy: "National Board of Examinations (NBE)",
      examDate: "January 2027",
      registrationDeadline: "November 15, 2026",
      officialUrl: "https://natboard.edu.in",
      stream: "Medical",
      description: "National Eligibility cum Entrance Test for MD/MS/Diploma and DNB CET for DrNB admissions across all medical institutions in India.",
      careerRelevance: "Admission to MD/MS specialisation courses at AIIMS, PGI Chandigarh, and all government and private medical colleges.",
    },
    {
      name: "XAT 2027",
      conductedBy: "XLRI Jamshedpur",
      examDate: "January 3, 2027",
      registrationDeadline: "November 30, 2026",
      officialUrl: "https://xatonline.in",
      stream: "Commerce",
      description: "Xavier Aptitude Test for MBA admissions to XLRI Jamshedpur, XIMB, XIME, and 150+ B-schools that accept XAT scores across India.",
      careerRelevance: "Admission to XLRI, one of India's top B-schools for HR and Business Management with strong placement record.",
    },
    {
      name: "JEE Main 2027 — Session 1",
      conductedBy: "National Testing Agency (NTA)",
      examDate: "January 22–30, 2027",
      registrationDeadline: "November 20, 2026",
      officialUrl: "https://jeemain.nta.ac.in",
      stream: "Engineering",
      description: "Joint Entrance Examination (Main) is the gateway to NITs, IIITs, and CFTIs for B.E./B.Tech/B.Arch programmes. Session 1 is held in January.",
      careerRelevance: "Admission to 31 NITs, 26 IIITs, and 28 CFTIs across India. Also qualifies for JEE Advanced.",
    },
    {
      name: "UPSC Civil Services Prelims 2027",
      conductedBy: "Union Public Service Commission (UPSC)",
      examDate: "June 6, 2027",
      registrationDeadline: "February 20, 2027",
      officialUrl: "https://upsc.gov.in",
      stream: "all",
      description: "Preliminary examination for IAS, IPS, IFS, and other Group A & B central services. Paper I is GS and Paper II is CSAT (qualifying).",
      careerRelevance: "Gateway to IAS, IPS, IFS, IRS and other prestigious All India Services — the most respected civil services in India.",
    },
    {
      name: "NEET UG 2027",
      conductedBy: "National Testing Agency (NTA)",
      examDate: "May 2, 2027",
      registrationDeadline: "February 7, 2027",
      officialUrl: "https://neet.nta.ac.in",
      stream: "Medical",
      description: "National Eligibility cum Entrance Test for MBBS, BDS, AYUSH, and other medical/dental undergraduate courses across India including AIIMS and JIPMER.",
      careerRelevance: "Only entrance for MBBS/BDS admissions across all medical colleges in India. Required for AIIMS, JIPMER, and state medical seats.",
    },
    {
      name: "JEE Advanced 2027",
      conductedBy: "IIT Madras (2027 organising institute)",
      examDate: "May 23, 2027",
      registrationDeadline: "May 2, 2027",
      officialUrl: "https://jeeadv.ac.in",
      stream: "Engineering",
      description: "The most prestigious engineering entrance exam in India. Only top 2.5 lakh JEE Main qualifiers can appear. Gateway to all 23 IITs.",
      careerRelevance: "Admission to IITs for B.Tech, B.Arch, B.S., and Dual Degree programmes — the highest ranked institutions in India.",
    },
    {
      name: "CUET UG 2027",
      conductedBy: "National Testing Agency (NTA)",
      examDate: "May 2027",
      registrationDeadline: "March 15, 2027",
      officialUrl: "https://cuet.samarth.ac.in",
      stream: "all",
      description: "Common University Entrance Test for undergraduate admissions to all 45 Central Universities including Delhi University, JNU, BHU, Hyderabad University.",
      careerRelevance: "Single exam for admission to DU, JNU, BHU, Hyderabad University, and all central universities — replaces college-wise cut-offs.",
    },
  ]);
  console.log("Exams seeded.");

  // ─── RESOURCES ───────────────────────────────────────────────────────────────
  await db.insert(resourcesTable).values([
    {
      title: "NPTEL Online Courses",
      platform: "NPTEL",
      url: "https://nptel.ac.in/courses",
      type: "Course",
      stream: "all",
      language: "English & Hindi",
      description: "1,900+ free video courses from IITs and IISc covering Engineering, Sciences, Management, Humanities. Earn government-recognised certificates by clearing NPTEL exams (proctored, fee ₹1,000).",
    },
    {
      title: "SWAYAM — Free Degree-Level Courses",
      platform: "SWAYAM",
      url: "https://swayam.gov.in",
      type: "Course",
      stream: "all",
      language: "English & Regional",
      description: "India's national MOOC platform with 4,000+ courses from school to post-graduate level. All courses are free. Credit transfer option available for enrolled college students.",
    },
    {
      title: "Khan Academy — Complete K-12 & Beyond",
      platform: "Khan Academy",
      url: "https://khanacademy.org",
      type: "Course",
      stream: "Science",
      language: "English & Hindi",
      description: "Free world-class education in Maths, Science, Computing, Economics. Includes full SAT prep, GMAT prep. Khan Academy in Hindi covers Class 6–12 NCERT syllabus.",
    },
    {
      title: "NCERT e-Textbooks (Class 1–12)",
      platform: "NCERT",
      url: "https://ncert.nic.in/textbook.php",
      type: "Book",
      stream: "all",
      language: "English & Hindi",
      description: "Free PDF downloads of all NCERT textbooks from Class 1 to 12 — the foundation for UPSC, JEE, NEET, and board exams. Also available in regional languages.",
    },
    {
      title: "e-PG Pathshala — Post Graduate Courses",
      platform: "e-PG Pathshala",
      url: "https://epgp.inflibnet.ac.in",
      type: "Course",
      stream: "all",
      language: "English",
      description: "UGC-funded portal with 23,000+ e-content modules for 70+ PG subjects. Useful for students preparing for UGC NET and those pursuing MA/MSc/MCom.",
    },
    {
      title: "MIT OpenCourseWare — Free MIT Education",
      platform: "MIT OCW",
      url: "https://ocw.mit.edu",
      type: "Course",
      stream: "Engineering",
      language: "English",
      description: "Free lecture notes, assignments, exams, and video lectures from MIT's actual courses — Computer Science, Mathematics, Physics, Engineering. No login required.",
    },
    {
      title: "Coursera — Free Audit Mode",
      platform: "Coursera",
      url: "https://coursera.org",
      type: "Course",
      stream: "all",
      language: "English",
      description: "Audit thousands of university courses from IITs, Google, IBM, Stanford, Yale for free. Paid certificate available but learning content is freely accessible.",
    },
    {
      title: "DIKSHA — Teachers & Students Platform",
      platform: "DIKSHA",
      url: "https://diksha.gov.in",
      type: "Course",
      stream: "all",
      language: "22 Indian languages",
      description: "Ministry of Education's national platform with thousands of pieces of e-content, textbooks, and courses in 22 Indian languages aligned with NCERT curriculum.",
    },
    {
      title: "Unacademy — Free Classes",
      platform: "Unacademy",
      url: "https://unacademy.com",
      type: "Video",
      stream: "all",
      language: "English & Hindi",
      description: "Free live classes and video lessons for UPSC, JEE, NEET, banking, SSC from India's top educators. Subscription required for advanced content but many classes are free.",
    },
    {
      title: "ClearIAS — UPSC Free Resources",
      platform: "ClearIAS",
      url: "https://clearias.com",
      type: "Course",
      stream: "all",
      language: "English",
      description: "Free study materials, current affairs notes, mock tests, and strategy guides for UPSC Civil Services Prelims and Mains. Trusted by thousands of IAS aspirants.",
    },
    {
      title: "IIT JEE Lectures — YouTube Playlist",
      platform: "YouTube",
      url: "https://youtube.com/@Etoosindia",
      type: "Video",
      stream: "Engineering",
      language: "English & Hindi",
      description: "Free JEE Main and Advanced video lectures covering Physics, Chemistry, and Mathematics from NV Sir, GB Sir, and other top kota faculty on YouTube.",
    },
    {
      title: "NEET Biology — YouTube by Neela Bakore",
      platform: "YouTube",
      url: "https://youtube.com/@NBTutorials",
      type: "Video",
      stream: "Medical",
      language: "English",
      description: "Complete NEET Biology lectures covering NCERT Class 11 and 12 chapters — Botany and Zoology. One of the most popular free NEET Biology resources in India.",
    },
    {
      title: "PW (Physics Wallah) Free Lectures",
      platform: "Physics Wallah",
      url: "https://pw.live",
      type: "Video",
      stream: "Engineering",
      language: "Hindi & English",
      description: "Free Physics, Chemistry, and Maths video lectures for JEE and NEET by Alakh Pandey. Extremely popular for making quality education affordable for all students.",
    },
    {
      title: "StudyIQ — UPSC & SSC Preparation",
      platform: "StudyIQ",
      url: "https://studyiq.com",
      type: "Video",
      stream: "all",
      language: "Hindi & English",
      description: "Free current affairs, UPSC, SSC CGL, banking, and state PCS preparation videos. Includes free PDFs and notes for government exam aspirants.",
    },
    {
      title: "National Digital Library of India",
      platform: "NDL India",
      url: "https://ndl.iitkgp.ac.in",
      type: "Book",
      stream: "all",
      language: "Multiple languages",
      description: "IIT Kharagpur's digital library aggregating 6 crore+ learning resources — books, articles, audio, video — spanning all subjects and education levels. Completely free.",
    },
  ]);
  console.log("Resources seeded.");

  // ─── MENTORS ─────────────────────────────────────────────────────────────────
  await db.insert(mentorsTable).values([
    {
      name: "Ananya Krishnan",
      title: "Software Engineer at Google India",
      college: "IIT Madras — B.Tech Computer Science (2021)",
      careerDomain: "Engineering",
      background: "First-gen from a farming family in Tirunelveli, Tamil Nadu. Father is an agricultural labourer. Scored 98.7 percentile in JEE Main.",
      contactUrl: "https://linkedin.com",
      availability: "Weekends (IST 10am–12pm)",
      bio: "I was the first in my village to go to an IIT. No coaching, no tutor — just NPTEL and PDFs. I know how hard it is when there's no one at home who understands your journey. Happy to guide anyone on JEE preparation, IIT life, and tech careers.",
    },
    {
      name: "Mohammed Irfan Shaikh",
      title: "IAS Officer — District Collector, Nashik",
      college: "UPSC CSE — AIR 47 | Grad: Govt. College Aurangabad",
      careerDomain: "Civil Services",
      background: "First-gen graduate from a lower-middle-class family in Aurangabad, Maharashtra. Father runs a small tailoring shop. Cleared UPSC in second attempt with zero coaching.",
      contactUrl: "https://linkedin.com",
      availability: "Saturday mornings only",
      bio: "I cleared UPSC with free resources — NCERT, The Hindu, and ClearIAS. I had no mentor, no coaching, and no money. That's exactly why I mentor students today. If I could do it, so can you. I focus on strategy, newspaper reading habits, and answer writing.",
    },
    {
      name: "Priya Devi Meena",
      title: "MBBS Doctor — AIIMS Jodhpur",
      college: "AIIMS Jodhpur — MBBS | From: Barmer, Rajasthan",
      careerDomain: "Medical",
      background: "ST student from a remote village in Barmer, Rajasthan. First woman in her extended family to become a doctor. Prepared for NEET using library books and YouTube.",
      contactUrl: "https://linkedin.com",
      availability: "Tuesdays & Thursdays 7–9pm IST",
      bio: "I want to tell every girl from a small town: AIIMS is possible for you too. I'll help you understand the NEET syllabus, reservation benefits, and how to manage studies without private coaching. I also guide on AIIMS hostel life and financial aid.",
    },
    {
      name: "Rahul Paswan",
      title: "Software Developer at Infosys | Ex-TCS",
      college: "NIT Patna — B.Tech ECE (2020)",
      careerDomain: "Engineering",
      background: "SC student from Muzaffarpur, Bihar. Father is a daily wage worker. Got NIT through JEE Main and secured campus placement via competitive programming practice.",
      contactUrl: "https://linkedin.com",
      availability: "Every Sunday 2–4pm IST",
      bio: "Campus placements were the most stressful part of NIT for me. I'll help you prepare for technical interviews, understand DSA, and navigate the campus placement process — from resume to offer letter. Also happy to talk about JEE prep without coaching.",
    },
    {
      name: "Deepika Murmu",
      title: "Advocate — Calcutta High Court",
      college: "National Law University Odisha — BBA.LLB (2019)",
      careerDomain: "Law",
      background: "ST student from Mayurbhanj, Odisha. First in family to attend a National Law University. Cleared CLAT in first attempt while studying in a government school.",
      contactUrl: "https://linkedin.com",
      availability: "Fridays 6–8pm IST",
      bio: "I had never heard of CLAT until Class 11. I figured it out on my own using free online resources. I mentor students on CLAT preparation, NLU life, understanding constitutional law basics, and how to build a legal career from a non-elite background.",
    },
    {
      name: "Karthik Rajan",
      title: "Data Scientist at Flipkart",
      college: "IIT Delhi — M.Tech AI & ML (2022) | BITS Pilani B.Tech (2020)",
      careerDomain: "Engineering",
      background: "OBC student from Coimbatore, Tamil Nadu. Father is an electrician. Funded B.Tech through AICTE scholarship and GATE fellowship for M.Tech.",
      contactUrl: "https://linkedin.com",
      availability: "Weekdays 9–10pm IST",
      bio: "I'll help you understand the path from B.Tech to IIT M.Tech via GATE — a route that's completely free if you get a GATE fellowship. Also guide on data science career paths, relevant free courses (Coursera, Kaggle), and how to build your portfolio with zero money.",
    },
    {
      name: "Sunita Bai Verma",
      title: "Assistant Professor — Delhi University",
      college: "JNU — M.A. & Ph.D. Sociology (2018) | UGC NET JRF",
      careerDomain: "Civil Services",
      background: "OBC student from a village in Chhattisgarh. First-gen graduate and the first PhD in her district. Funded entirely through UGC-JRF fellowship.",
      contactUrl: "https://linkedin.com",
      availability: "Mondays & Wednesdays 7–9pm IST",
      bio: "I'll guide students who want to pursue academics — from clearing UGC NET, getting JRF fellowship, PhD admission at JNU/HCU, to getting assistant professor posts. Also help with UPSC Optional (Sociology). Being first-gen in academia is hard but very possible.",
    },
    {
      name: "Vijay Kumar Chamar",
      title: "Chartered Accountant — Big4 (Deloitte)",
      college: "CA Final | B.Com: Govt. College Jaipur",
      careerDomain: "Management",
      background: "SC student from Jaipur. Father works as a municipal sweeper. Cleared CA in two attempts while coaching himself using ICAI study material. No paid coaching.",
      contactUrl: "https://linkedin.com",
      availability: "Saturdays 11am–1pm IST",
      bio: "CA is one of the most respected and well-paying careers you can build without an engineering or MBA degree. I'll help you understand the CA route — Foundation, Intermediate, Final — articleship tips, passing strategies, and Big4 career paths. All free guidance.",
    },
    {
      name: "Lakshmi Narayanan S",
      title: "Research Engineer — ISRO Satellite Centre",
      college: "IIT Bombay — M.Tech Aerospace (2017) | NIT Trichy B.Tech",
      careerDomain: "Engineering",
      background: "MBC student from Thanjavur, Tamil Nadu. Father is a weaver. Got GATE rank 89 (Aerospace) after two years of self-study using free resources.",
      contactUrl: "https://linkedin.com",
      availability: "Sundays 10am–12pm IST",
      bio: "I work at ISRO and it's everything I dreamed of. I guide students who want careers in core engineering — aerospace, mechanical, civil — through GATE, PSU exams, and M.Tech at IITs. Also talk about ISRO recruitment and what working there is really like.",
    },
    {
      name: "Fatima Shaikh",
      title: "Senior Manager — HDFC Bank",
      college: "MBA Finance: XLRI Jamshedpur (2016) | B.Com: Mumbai University",
      careerDomain: "Management",
      background: "Muslim girl from a conservative family in Bandra, Mumbai. First woman in family to do an MBA. Cleared XAT and CAT simultaneously while working part-time.",
      contactUrl: "https://linkedin.com",
      availability: "Thursday evenings 8–10pm IST",
      bio: "I'll help you navigate MBA entrances — CAT, XAT, SNAP — and guide you on B-school selection, finance careers, and how to handle family pressure while chasing professional ambitions. Women from conservative families especially welcome — I understand your specific challenges.",
    },
  ]);
  console.log("Mentors seeded.");

  console.log("\n✅ Real dataset seeded successfully!");
  await pool.end();
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
